s3 replication module
Seagate/cortx-multisite pull request #1
Opened 2021-05-03 04:45 UTC by rajkumarpatel2602

Changes :
1. s3 Replicator and replication manager along with client code for testing.
2. Logging mechanism with rotation
3. Makefile, requirements.txt and flake8 check support
4. Yaml configuration file for replicator and replication manager

ToDo :
1. Adding relative path for the log.py

2021-05-03 13:47 UTC, kaustubh-d requested changes

2021-05-03 17:49 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/manager_conf.yaml
> +   log_file: "manager_logging.out"
done

2021-05-03 17:51 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/manager_conf.yaml
> +   manager_logger_name: "s3_replication_manager"
done

2021-05-03 17:52 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/manager_conf_init.py
> +class config():
done

2021-05-03 18:00 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/manager_conf_init.py
> +    rep_conf = None
done

2021-05-03 18:01 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/scheduler.py
> +async def get_job_attr(request):
done

2021-05-03 18:03 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/scheduler.py
> +    id = (request.match_info['job_id'])
done

2021-05-03 18:04 UTC, rajkumarpatel2602 commented on s3/replication/manager/src/scheduler.py
> +async def add_jobs(request):
done

2021-05-06 05:09 UTC, rajkumarpatel2602 commented
Addressed all the comment along with restructuring changes in this [PR](https://github.com/Seagate/cortx-multisite/pull/5) and Hence closing this PR.

2021-05-06 05:09 UTC, closed without merging